  instance_type: t3.small
  users: 
    - 
      login: user1
      ssh_key: ssh-rsa <user-public-key-here> user1@localhost
  volumes: 
    - 
      device: /dev/xvda
      mount: /
      size_gb: 10
      type: ext4
    - 
      device: /dev/xvdf
      mount: /data
      size_gb: 100
      type: xfs